-- 初期化、作り直し用の削除 --
CONN whisper/bbs
DROP TABLE POST;
DROP SEQUENCE POST_CNT;
CONN system/orcl
DROP USER whisper CASCADE;


--削除--
--DROP TABLESPACE cosmos INCLUDING CONTENTS AND DATAFILES;

--ALTER TABLESPACE cosmos OFFLINE;

SHUTDOWN IMMEDIATE;