-- 初期化、作り直し用の削除 --
DROP USER whisper CASCADE;

-- 初期化、作り直し用の削除 --
DROP TABLE POST;
DROP SEQUENCE POST_CNT;


--削除--
DROP TABLESPACE cosmos INCLUDING CONTENTS AND DATAFILES;

ALTER TABLESPACE cosmos OFFLINE;

SHUTDOWN IMMEDIATE;